version: "3"

services:
  frontend:
    build:
      context: ./fa-frontend
    image: fa-frontend:${UI_TAG}
  reverseproxy:
    build:
      context: ./fa-reverseproxy
    image: fa-reverseproxy:${PROXY_TAG}
  backend-user:
    build:
      context: ./fa-user-server
    image: fa-user-server:${USER_TAG}
  backend-player:
    build:
      context: ./fa-player-server
    image: fa-player-server:${PLAYER_TAG}
