version: "3"

services:
  frontend:
    image: fa-frontend:${UI_TAG}
    ports:
      - "3000:80"

  reverseproxy:
      image: fa-reverseproxy:${PROXY_TAG}
      ports:
          - 4000:4000
      restart: always
      depends_on:
        - backend-user
        - backend-player
  backend-user:
    image: fa-user-server:${USER_TAG}
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      APP_URL: "http://localhost:3000"
  backend-player:
    image: fa-player-server:${PLAYER_TAG}
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      APP_URL: "http://localhost:3000"
