version: "3"

services:
  frontend:
    build:
      context: ./fa-frontend
    image: fa-frontend:${UI_TAG}
  backend-user:
    build:
      context: ./fa-user-server
    image: fa-user-server:${USER_TAG}
