apiVersion: v1
kind: Service
metadata:
  name: backend-player-svc
  labels:
    service: fa-player-server
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: fa-player-server
  type: ClusterIP