apiVersion: v1
kind: Service
metadata:
  name: backend-auth-svc
  labels:
    service: fa-user-server
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: fa-user-server
  type: ClusterIP