apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: fa-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fa-frontend
  template:
    metadata:
      labels:
        app: fa-frontend
    spec:
      containers:
      - name: frontend
        image: gauravsinghaec/fa-frontend:v4
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 1.5Gi