apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-svc
  labels:
    service: fa-reverseproxy
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    service: fa-reverseproxy
  type: ClusterIP